"""Equipment slot and item metadata for Idleon exports."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, kw_only=True)
class EquipmentSlot:
    """Description for one fixed EquipOrder slot."""

    key: str
    group_index: int
    slot_index: int
    label: str


MAIN_EQUIPMENT_SLOTS = (
    EquipmentSlot(key="equipped_helmet", group_index=0, slot_index=0, label="Helmet"),
    EquipmentSlot(key="equipped_weapon", group_index=0, slot_index=1, label="Weapon"),
    EquipmentSlot(key="equipped_shirt", group_index=0, slot_index=2, label="Shirt"),
    EquipmentSlot(
        key="equipped_necklace", group_index=0, slot_index=3, label="Necklace"
    ),
    EquipmentSlot(key="equipped_pants", group_index=0, slot_index=4, label="Pants"),
    EquipmentSlot(key="equipped_ring_1", group_index=0, slot_index=5, label="Ring 1"),
    EquipmentSlot(key="equipped_boots", group_index=0, slot_index=6, label="Boots"),
    EquipmentSlot(key="equipped_ring_2", group_index=0, slot_index=7, label="Ring 2"),
    EquipmentSlot(
        key="equipped_premium_helmet",
        group_index=0,
        slot_index=8,
        label="Premium helmet",
    ),
    EquipmentSlot(
        key="equipped_keychain_1", group_index=0, slot_index=9, label="Keychain 1"
    ),
    EquipmentSlot(key="equipped_trophy", group_index=0, slot_index=10, label="Trophy"),
    EquipmentSlot(
        key="equipped_keychain_2", group_index=0, slot_index=11, label="Keychain 2"
    ),
    EquipmentSlot(key="equipped_cape", group_index=0, slot_index=12, label="Cape"),
    EquipmentSlot(
        key="equipped_chat_ring", group_index=0, slot_index=13, label="Chat ring"
    ),
    EquipmentSlot(
        key="equipped_name_tag", group_index=0, slot_index=14, label="Name tag"
    ),
    EquipmentSlot(key="equipped_attire", group_index=0, slot_index=15, label="Attire"),
)

TOOL_EQUIPMENT_SLOTS = (
    EquipmentSlot(key="equipped_pickaxe", group_index=1, slot_index=0, label="Pickaxe"),
    EquipmentSlot(key="equipped_hatchet", group_index=1, slot_index=1, label="Hatchet"),
    EquipmentSlot(
        key="equipped_fishing_rod", group_index=1, slot_index=2, label="Fishing rod"
    ),
    EquipmentSlot(
        key="equipped_bug_catching_net",
        group_index=1,
        slot_index=3,
        label="Bug catching net",
    ),
    EquipmentSlot(
        key="equipped_trap_box", group_index=1, slot_index=4, label="Trap box"
    ),
    EquipmentSlot(
        key="equipped_worship_skull", group_index=1, slot_index=5, label="Worship skull"
    ),
    EquipmentSlot(
        key="equipped_dna_splicer", group_index=1, slot_index=6, label="DNA splicer"
    ),
)

EQUIPMENT_ITEM_LABELS = {
    "CatchingNet1": "Bug Net",
    "CatchingNet10": "Dreadlo Matted Netting",
    "CatchingNet11": "Marbiglass Netting",
    "CatchingNet12": "Wrangler of the Qoxzul",
    "CatchingNet13": "Prehistoric Netting",
    "CatchingNet2": "Copper Netted Net",
    "CatchingNet3": "Reinforced Net",
    "CatchingNet4": "Golden Net",
    "CatchingNet5": "Platinet",
    "CatchingNet6": "Dementia Net",
    "CatchingNet7": "Void Imperium Net",
    "CatchingNet8": "Lustre Netting",
    "CatchingNet9": "Starfire Trim Netting",
    "DNAgun0": "Sappy DNA Splicer",
    "DNAgun1": "Bolstered DNA Splicer",
    "DNAgun2": "Double Barreled DNA Splicer",
    "DNAgun3": "Ergonomic DNA Splicer",
    "EquipmentBows1": "Wooden Bow",
    "EquipmentBows10": "Diabolical Continuit",
    "EquipmentBows11": "Sediment Core Grunkler",
    "EquipmentBows12": "Spine Tingler Sniper",
    "EquipmentBows13": "Pristine Longbow",
    "EquipmentBows14": "Doublestring Godshooter",
    "EquipmentBows15": "Raptor Shardslinger",
    "EquipmentBows3": "Birch Longbow",
    "EquipmentBows4": "Carrot Launcher",
    "EquipmentBows5": "Spiked Menace",
    "EquipmentBows6": "Pharaoh Bow",
    "EquipmentBows7": "Blizzard Bow",
    "EquipmentBows8": "Blackhole Bow",
    "EquipmentBows9": "Shardsure Leif",
    "EquipmentBowsTempest0": "Tempest Bow of Dust",
    "EquipmentBowsTempest1": "Tempest Bow of Ice",
    "EquipmentBowsTempest2": "Tempest Bow of Fire",
    "EquipmentBowsTempest3": "Tempest Bow of Wind",
    "EquipmentBowsTempest4": "Tempest Bow of Grass",
    "EquipmentCape0": "Angel Wings",
    "EquipmentCape1": "Lava Wings",
    "EquipmentCape10": "Giant Starflower",
    "EquipmentCape11": "Riftwalker Wings",
    "EquipmentCape12": "Blooming Vine",
    "EquipmentCape13": "Eternal Flames of The Divine",
    "EquipmentCape14": "Phoenix Wings",
    "EquipmentCape15": "Giant Nightshade",
    "EquipmentCape16": "Timeless Watch",
    "EquipmentCape17": "Gilded Emperor Wings",
    "EquipmentCape18": "Chains of the Gilded Vaultguard",
    "EquipmentCape19": "Dragonroll Mantlepiece",
    "EquipmentCape2": "Easter Egg Backpack",
    "EquipmentCape20": "Beeg Egg",
    "EquipmentCape3": "Radiant Amarok Backstabber",
    "EquipmentCape4": "Gilded Efaunt Dislodged Tusks",
    "EquipmentCape5": "Blighted Chizoar Shard Cape",
    "EquipmentCape6": "Cascading Scaled Cape of Krieg",
    "EquipmentCape7": "Molten Cloak",
    "EquipmentCape8": "Giant Rose",
    "EquipmentCape9": "Giant Violet",
    "EquipmentGown0": "Pyromancer Robes",
    "EquipmentGown1": "Cobalt Robe",
    "EquipmentGown2": "Abyssal Robe",
    "EquipmentGown3": "Evergreen Robe",
    "EquipmentGown4": "Silkshard Robe",
    "EquipmentGown5": "Corsair Uniform",
    "EquipmentGown6": "Bulwark Armor",
    "EquipmentGown7": "Time Traveler Outfit",
    "EquipmentHats1": "Farmer Brim",
    "EquipmentHats10": "Pink Headband",
    "EquipmentHats100": "Fiery Mane",
    "EquipmentHats101": "Guardian Mane",
    "EquipmentHats102": "Fanned Blossomage",
    "EquipmentHats103": "Dainty Brim",
    "EquipmentHats104": "Charcoal Hat",
    "EquipmentHats105": "Marbiglass Headdress",
    "EquipmentHats106": "Crown of the Gods",
    "EquipmentHats107": "Shiny Bored Beanie",
    "EquipmentHats108": "3rd Anniversary Ice Cream Topper",
    "EquipmentHats109": "Husky Hat",
    "EquipmentHats11": "Grey Beret",
    "EquipmentHats110": "Yellow Beanie",
    "EquipmentHats111": "Epic Santa Hat",
    "EquipmentHats112": "Deathbringer Hood of Death",
    "EquipmentHats113": "Pink Beanie",
    "EquipmentHats114": "True Crown",
    "EquipmentHats115": "Celebration Mane",
    "EquipmentHats116": "Goldberry",
    "EquipmentHats117": "Orange Beanie",
    "EquipmentHats118": "Windwalker Hood",
    "EquipmentHats119": "Emperor Kabuto",
    "EquipmentHats12": "Traffic Cone",
    "EquipmentHats120": "Umbrella Brim",
    "EquipmentHats121": "Bloo Creamer",
    "EquipmentHats122": "Arcanist Crown",
    "EquipmentHats123": "Prehistoric Battlehair",
    "EquipmentHats124": "Alpine Beanie",
    "EquipmentHats125": "Rudolph Antlers",
    "EquipmentHats126": "Helper Elf Hat",
    "EquipmentHats127": "Seal Team Skipper Hat",
    "EquipmentHats128": "Lovely Top Hat",
    "EquipmentHats129": "Polkadot Beanie",
    "EquipmentHats13": "Propeller Cap",
    "EquipmentHats130": "Leprechaun Hat",
    "EquipmentHats131": "Lucky Ducky Brim",
    "EquipmentHats132": "Time Traveler Top Hat",
    "EquipmentHats133": "Native Headdress",
    "EquipmentHats134": "Starry Hairpins",
    "EquipmentHats135": "Blonde Hairpiece",
    "EquipmentHats136": "Bronze Tournament Spike Hat",
    "EquipmentHats137": "Silver Tournament Spike Hat",
    "EquipmentHats138": "Gold Tournament Spike Hat",
    "EquipmentHats139": "Sun Hat",
    "EquipmentHats14": "Baseball Hat",
    "EquipmentHats15": "Leather Cap",
    "EquipmentHats16": "Top Hat",
    "EquipmentHats17": "Copper Helmet",
    "EquipmentHats18": "Iron Helmet",
    "EquipmentHats19": "Platinum Helmet",
    "EquipmentHats2": "Royal Turban",
    "EquipmentHats20": "Militia Helm",
    "EquipmentHats21": "Birthday Hat",
    "EquipmentHats22": "Amarok Helmet",
    "EquipmentHats23": "Farmer Brimer",
    "EquipmentHats24": "Farmer Brimest",
    "EquipmentHats25": "Bored Beanie",
    "EquipmentHats26": "Witch Hat",
    "EquipmentHats27": "Paper Boat",
    "EquipmentHats28": "Gold Helmet",
    "EquipmentHats29": "Alien Headband",
    "EquipmentHats3": "Thief Hood",
    "EquipmentHats30": "Cowbo Galloneer",
    "EquipmentHats31": "Smitty's Bubble Blowing Hat",
    "EquipmentHats32": "Bandit Bob Mask",
    "EquipmentHats33": "Paper Bag",
    "EquipmentHats34": "Parasite",
    "EquipmentHats35": "Diamond Horns",
    "EquipmentHats36": "Halloween Pumpkin",
    "EquipmentHats37": "Hotdog Hero",
    "EquipmentHats38": "Invisible Hat",
    "EquipmentHats39": "Grandma Disguise",
    "EquipmentHats40": "Pardoned Turkey",
    "EquipmentHats41": "Sleek Coif",
    "EquipmentHats42": "Santa Hat",
    "EquipmentHats43": "Snowman",
    "EquipmentHats44": "Jar",
    "EquipmentHats45": "Giftmas Tree",
    "EquipmentHats46": "Strawbiggy",
    "EquipmentHats47": "Pop Cat",
    "EquipmentHats48": "Dairy Dunk",
    "EquipmentHats49": "The Classic",
    "EquipmentHats4Choppin": "Stump Prop",
    "EquipmentHats5": "White Headband",
    "EquipmentHats50": "Green Beanie",
    "EquipmentHats51": "Big Pretty Bow",
    "EquipmentHats52": "Efaunt Helmet",
    "EquipmentHats53": "Dementia Helmet",
    "EquipmentHats54": "Void Imperium Helmet",
    "EquipmentHats55": "Steam Cap",
    "EquipmentHats56": "Bunny Ears",
    "EquipmentHats57": "Big Bunny",
    "EquipmentHats58": "Murmillo Helm",
    "EquipmentHats59": "Conquistador Plume",
    "EquipmentHats6": "Green Headband",
    "EquipmentHats60": "Adornment of the High Priest",
    "EquipmentHats61": "Mark of Member",
    "EquipmentHats62": "Fluffy Ramsy",
    "EquipmentHats63": "Summer Shell",
    "EquipmentHats64": "Nuget Cake Fedora",
    "EquipmentHats65": "The Red Boaty",
    "EquipmentHats66": "Honker Hat",
    "EquipmentHats67": "Acorn Topper",
    "EquipmentHats68": "Chizoar Helmet",
    "EquipmentHats69": "Giftmas Snoozy Cap",
    "EquipmentHats7": "Red Headband",
    "EquipmentHats70": "Lustre Veil",
    "EquipmentHats71": "Diabolical Headcase",
    "EquipmentHats72": "Nondescript Game Show Host Hair",
    "EquipmentHats73": "Real Civil Engineer Helmet",
    "EquipmentHats74": "Thin Veil of The Troll",
    "EquipmentHats75": "Apple Launch Hat",
    "EquipmentHats76": "Funny Hat",
    "EquipmentHats77": "Magma Core Headdress",
    "EquipmentHats78": "Meteorhead",
    "EquipmentHats79": "Ice Guard Helmet",
    "EquipmentHats8": "Purple Tupacband",
    "EquipmentHats80": "Corgi Topper",
    "EquipmentHats81": "Siege Captain Cap",
    "EquipmentHats82": "Ele Sorcerer Pointed Hat",
    "EquipmentHats83": "Skulled Helmet of the Divine",
    "EquipmentHats84": "The Crow Perch",
    "EquipmentHats85": "Bedsheet with Holes",
    "EquipmentHats86": "Carrotman Mask",
    "EquipmentHats87": "Glublin Mask",
    "EquipmentHats88": "Bloque Mask",
    "EquipmentHats89": "Borzoi Topper",
    "EquipmentHats9": "Yellow Headband",
    "EquipmentHats90": "Straw Hat",
    "EquipmentHats91": "Wig Bandana",
    "EquipmentHats92": "Funky Hat",
    "EquipmentHats93": "Reinforced Headband",
    "EquipmentHats94": "Shogun Helmet",
    "EquipmentHats95": "Gilded Headband",
    "EquipmentHats96": "Bamboo Hat",
    "EquipmentHats97": "Festive Beast Mask",
    "EquipmentHats98": "Heiress Headdress",
    "EquipmentHats99": "Spirited Mane",
    "EquipmentHatsBeg1": "Ice Cream Sundae",
    "EquipmentKeychain0": "Simple Key Chain",
    "EquipmentKeychain1": "Leafy Chain",
    "EquipmentKeychain10": "Cactus Chain",
    "EquipmentKeychain11": "Relic Chain",
    "EquipmentKeychain12": "Balloon Dog Chain",
    "EquipmentKeychain13": "Frozen Tart Chain",
    "EquipmentKeychain14": "Whatamelon Chain",
    "EquipmentKeychain15": "9 Ball Chain",
    "EquipmentKeychain16": "Pincer Hand Chain",
    "EquipmentKeychain17": "Gilded Key Chain",
    "EquipmentKeychain18": "Sushi Chain",
    "EquipmentKeychain19": "Time Candy Chain",
    "EquipmentKeychain2": "Red Sneaker Chain",
    "EquipmentKeychain20": "Star Blobulyte Galaxy Chain",
    "EquipmentKeychain21": "Mmm Donut Chain",
    "EquipmentKeychain22": "Negative 7 Chain",
    "EquipmentKeychain23": "Diamond Honker Chain",
    "EquipmentKeychain24": "BobGoldPickle Chain",
    "EquipmentKeychain25": "Eye Owe Ess Chain",
    "EquipmentKeychain26": "Key to Desert Chain",
    "EquipmentKeychain27": "Key to Mountains Chain",
    "EquipmentKeychain28": "Key to Purgatory Chain",
    "EquipmentKeychain29": "Spiritlord Horn Chain",
    "EquipmentKeychain3": "Wartooth Chain",
    "EquipmentKeychain4": "8 Ball Chain",
    "EquipmentKeychain5": "Piggy Chain",
    "EquipmentKeychain6": "Dumbphone Chain",
    "EquipmentKeychain7": "Horn Chain",
    "EquipmentKeychain8": "Rustic Key Chain",
    "EquipmentKeychain9": "Taco Chain",
    "EquipmentNametag1": "Riftwalker Nametag",
    "EquipmentNametag10": "3rd Anniversary IdleOn Nametag",
    "EquipmentNametag11": "Nightshade Nametag",
    "EquipmentNametag12": "Megafeather Nametag",
    "EquipmentNametag13": "Timeless Nametag",
    "EquipmentNametag14": "Snowflake Nametag",
    "EquipmentNametag15": "Frostyman Nametag",
    "EquipmentNametag16": "Lovely Day Nametag",
    "EquipmentNametag17": "Spectacular 4th Year Nametag",
    "EquipmentNametag18": "4th Anniversary IdleOn Nametag",
    "EquipmentNametag19": "Aethermoon Nametag",
    "EquipmentNametag2": "Lava's Awesome Nametag",
    "EquipmentNametag20": "Deadbones Nametag",
    "EquipmentNametag21": "Treasure Nametag",
    "EquipmentNametag22": "Tome Apprentice Nametag",
    "EquipmentNametag23": "Tome Journeyman Nametag",
    "EquipmentNametag24": "Tome Expert Nametag",
    "EquipmentNametag25": "Tome Elite Nametag",
    "EquipmentNametag26": "Tome Pro Nametag",
    "EquipmentNametag27": "Tome Master Nametag",
    "EquipmentNametag28": "Tome Legend Nametag",
    "EquipmentNametag29": "Reliquarium Nametag",
    "EquipmentNametag3": "Balling Nametag",
    "EquipmentNametag30": "Cropfall Nametag",
    "EquipmentNametag31": "Gingerbread Nametag",
    "EquipmentNametag32": "Sweet Chocolate Nametag",
    "EquipmentNametag33": "Pot of Gold Nametag",
    "EquipmentNametag34": "Emerald Nametag",
    "EquipmentNametag35": "5th Anniversary IdleOn Nametag",
    "EquipmentNametag36": "Wonderful 5th Year Nametag",
    "EquipmentNametag37": "Grand Egg Nametag",
    "EquipmentNametag4": "Vman Nametag",
    "EquipmentNametag41": "All That Glitters Nametag",
    "EquipmentNametag5": "Spring Flowers Nametag",
    "EquipmentNametag6b": "Trash Tuna Nametag",
    "EquipmentNametag7": "Island Adventurer Nametag",
    "EquipmentNametag8": "Summer Shovel Nametag",
    "EquipmentNametag9": "Falloween Nametag",
    "EquipmentNametagReplica0": "Replica Nametag",
    "EquipmentNametagReplica1": "Riftwalker Nametag",
    "EquipmentNametagReplica10": "3rd Anniversary IdleOn Nametag",
    "EquipmentNametagReplica11": "Nightshade Nametag",
    "EquipmentNametagReplica12": "Megafeather Nametag",
    "EquipmentNametagReplica13": "Timeless Nametag",
    "EquipmentNametagReplica14": "Snowflake Nametag",
    "EquipmentNametagReplica15": "Frostyman Nametag",
    "EquipmentNametagReplica16": "Lovely Day Nametag",
    "EquipmentNametagReplica17": "Spectacular 4th Year Nametag",
    "EquipmentNametagReplica18": "4th Anniversary IdleOn Nametag",
    "EquipmentNametagReplica19": "Aethermoon Nametag",
    "EquipmentNametagReplica2": "Lava's Awesome Nametag",
    "EquipmentNametagReplica20": "Deadbones Nametag",
    "EquipmentNametagReplica21": "Treasure Nametag",
    "EquipmentNametagReplica22": "Tome Apprentice Nametag",
    "EquipmentNametagReplica23": "Tome Journeyman Nametag",
    "EquipmentNametagReplica24": "Tome Expert Nametag",
    "EquipmentNametagReplica25": "Tome Elite Nametag",
    "EquipmentNametagReplica26": "Tome Pro Nametag",
    "EquipmentNametagReplica27": "Tome Master Nametag",
    "EquipmentNametagReplica28": "Tome Legend Nametag",
    "EquipmentNametagReplica29": "Reliquarium Nametag",
    "EquipmentNametagReplica3": "Balling Nametag",
    "EquipmentNametagReplica30": "Cropfall Nametag",
    "EquipmentNametagReplica31": "Gingerbread Nametag",
    "EquipmentNametagReplica32": "Sweet Chocolate Nametag",
    "EquipmentNametagReplica33": "Pot of Gold Nametag",
    "EquipmentNametagReplica34": "Emerald Nametag",
    "EquipmentNametagReplica35": "5th Anniversary IdleOn Nametag",
    "EquipmentNametagReplica36": "Wonderful 5th Year Nametag",
    "EquipmentNametagReplica37": "Grand Egg Nametag",
    "EquipmentNametagReplica38": "Bronze Tournament Border Nametag",
    "EquipmentNametagReplica39": "Silver Tournament Border Nametag",
    "EquipmentNametagReplica4": "Vman Nametag",
    "EquipmentNametagReplica40": "Gold Tournament Border Nametag",
    "EquipmentNametagReplica41": "All That Glitters Nametag",
    "EquipmentNametagReplica5": "Spring Flowers Nametag",
    "EquipmentNametagReplica6": "Trash Tuna Nametag",
    "EquipmentNametagReplica6b": "Trash Tuna Nametag",
    "EquipmentNametagReplica7": "Island Adventurer Nametag",
    "EquipmentNametagReplica8": "Summer Shovel Nametag",
    "EquipmentNametagReplica9": "Falloween Nametag",
    "EquipmentPants1": "Torn Jeans",
    "EquipmentPants10": "Give Up On Life Pants",
    "EquipmentPants11": "Yellow Belt Ninja Pants",
    "EquipmentPants12": "Merchantile Pants",
    "EquipmentPants13": "Ancient Leggings",
    "EquipmentPants14": "Forensic Leggings",
    "EquipmentPants15": "Bleached Designer Wode Patch Pants",
    "EquipmentPants16": "Adam's Leaf",
    "EquipmentPants17": "Amarok Hinds",
    "EquipmentPants18": "Dirty Coal Miner Baggy Soot Pants",
    "EquipmentPants19": "Trimmed Rune Platelegs",
    "EquipmentPants2": "Copper Platelegs",
    "EquipmentPants20": "Efaunt Hipilium",
    "EquipmentPants21": "Void Imperium Shardshins",
    "EquipmentPants22": "Fishing Overalls",
    "EquipmentPants23": "Bandito Pantaloon",
    "EquipmentPants24": "Lustre Scales",
    "EquipmentPants25": "Diabolical Trimed Leg Guards",
    "EquipmentPants26": "Magma Core Battleskirt",
    "EquipmentPants27": "Spiked Leggings of the Divine",
    "EquipmentPants29": "Marbiglass Legplates",
    "EquipmentPants3": "Iron Platelegs",
    "EquipmentPants30": "Tatters of the Gods",
    "EquipmentPants31": "Emperor Zubon",
    "EquipmentPants32": "Prehistoric Pantaloons",
    "EquipmentPants4": "Gold Platelegs",
    "EquipmentPants5": "Platinum Shins",
    "EquipmentPants6": "Dementia Shins",
    "EquipmentPants7": "Gilded Pilates",
    "EquipmentPants8": "Twisted Scales",
    "EquipmentPants9": "Chizoar Scaled Leggings",
    "EquipmentPendant1": "Mint Icey",
    "EquipmentPendant10": "Sleek Shank",
    "EquipmentPendant11": "Carrot Horror",
    "EquipmentPendant12": "Tarantulight",
    "EquipmentPendant13": "Quartz Pendant",
    "EquipmentPendant14": "Fuscismatia",
    "EquipmentPendant15": "Lucky Fish Head",
    "EquipmentPendant16": "Strung Bludgeon",
    "EquipmentPendant17": "Chaotic Amarok Pendant",
    "EquipmentPendant18": "Strung Steamy",
    "EquipmentPendant19": "Cedar Pendant",
    "EquipmentPendant2": "Strawbu Icey",
    "EquipmentPendant20": "Fishhead Pendant",
    "EquipmentPendant21": "Deathly Cluster Pendant",
    "EquipmentPendant22": "Hallowed Tail Pendant",
    "EquipmentPendant23": "Persephones Bouquet",
    "EquipmentPendant24": "Chizoars Blankie",
    "EquipmentPendant25": "Chizoars Caustic Scarf",
    "EquipmentPendant26": "Polished Bludgeon",
    "EquipmentPendant27": "Skullfish Pendant",
    "EquipmentPendant28": "Crescent Moon Pendant",
    "EquipmentPendant29": "Strung Tooth of the Divine",
    "EquipmentPendant3": "Rok Road Icey",
    "EquipmentPendant30": "The Divine Scarf",
    "EquipmentPendant31": "Deathbloom Flower Pendant",
    "EquipmentPendant32": "Slimy Necklace",
    "EquipmentPendant33": "Emerald Bling Pendant",
    "EquipmentPendant34": "Charred Pendant",
    "EquipmentPendant35": "Bramble of the Emperor",
    "EquipmentPendant36": "Butterfly Pendant",
    "EquipmentPendant4": "Rainbo Icey",
    "EquipmentPendant5": "Chocotastic Icey",
    "EquipmentPendant6": "Blubbery Icecream",
    "EquipmentPendant7": "Lava Icey",
    "EquipmentPendant8": "Legends Icey",
    "EquipmentPendant9": "Little Wooden Katana",
    "EquipmentPunching1": "Boxing Gloves",
    "EquipmentPunching10": "Pentastud Slapper",
    "EquipmentPunching11": "Mittens of the Gods",
    "EquipmentPunching12": "Talon of the Hawk",
    "EquipmentPunching2": "The Stingers",
    "EquipmentPunching3": "Bandage Wraps",
    "EquipmentPunching4": "Uninflated Glove",
    "EquipmentPunching5": "Eclectic Ordeal",
    "EquipmentPunching6": "Knuckle Sabers",
    "EquipmentPunching7": "Diabolical Gauntlet",
    "EquipmentPunching8": "Molten Core Knucklers",
    "EquipmentPunching9": "Crackled Skull Destroyer",
    "EquipmentRings1": "Gold Ring",
    "EquipmentRings10": "Spikeweed Ring",
    "EquipmentRings11": "Defenders Dignity",
    "EquipmentRings12": "Frisbee Ring",
    "EquipmentRings13": "Silver Stopwatch",
    "EquipmentRings14": "Dooble Goopi",
    "EquipmentRings15": "Sanic Ring",
    "EquipmentRings16": "Efaunt Trunculus",
    "EquipmentRings18": "The Emperor's Opal",
    "EquipmentRings19": "Bejeweled Ring",
    "EquipmentRings2": "Copper Band",
    "EquipmentRings20": "Rex Ring",
    "EquipmentRings21": "Elf Twist Ring",
    "EquipmentRings22": "Tenacity Ring",
    "EquipmentRings23": "Neutron Ice Ring",
    "EquipmentRings24": "Lab Ring",
    "EquipmentRings25": "Chef Ring",
    "EquipmentRings26": "Serrated Rex Ring",
    "EquipmentRings27": "Protectors Pride",
    "EquipmentRings28": "Midnight Stopwatch",
    "EquipmentRings29": "Dawn Stopwatch",
    "EquipmentRings3": "Steel Band",
    "EquipmentRings30": "Souped Lab Ring",
    "EquipmentRings31": "Tundra Killer Ring",
    "EquipmentRings32": "Nebula Killer Ring",
    "EquipmentRings33": "Dune Killer Ring",
    "EquipmentRings34": "Magma Killer Ring",
    "EquipmentRings35": "Zero Point Stopwatch",
    "EquipmentRings36": "Demented Emperor Opal",
    "EquipmentRings37": "Spirit Killer Ring",
    "EquipmentRings38": "Starstrut Ring",
    "EquipmentRings4": "Molden Crust",
    "EquipmentRings5": "Toxic Bubbles Band",
    "EquipmentRings6": "Death Wish",
    "EquipmentRings7": "Pugilist Demise",
    "EquipmentRings8": "The Used Bandaid",
    "EquipmentRings9": "Chat Ring",
    "EquipmentRingsArc0": "Cultist Ring",
    "EquipmentRingsChat1": "Love Ring",
    "EquipmentRingsChat10": "Meteorite Ring",
    "EquipmentRingsChat11": "Equinox Ring",
    "EquipmentRingsChat12": "Tournament Ring",
    "EquipmentRingsChat2": "Leafy Ring",
    "EquipmentRingsChat3": "Wealth Ring",
    "EquipmentRingsChat4": "Bob Ring",
    "EquipmentRingsChat5": "Bubble Ring",
    "EquipmentRingsChat6": "Cthulu's Ring",
    "EquipmentRingsChat8": "Lava Sez Buy More Gems",
    "EquipmentRingsChat9": "HONK Ring",
    "EquipmentRingsFishing1": "Shallow Watering",
    "EquipmentRingsFishing2": "Oceanic Ring",
    "EquipmentRingsFishing3": "Deepwater Trench Ring",
    "EquipmentRingsTempest0": "Tempest Ring of Leef",
    "EquipmentRingsTempest1": "Tempest Ring of Ice",
    "EquipmentRingsTempest2": "Tempest Ring of Lava",
    "EquipmentRingsTempest3": "Tempest Ring of Carbon",
    "EquipmentRingsTempest4": "Tempest Ring of Power",
    "EquipmentRingsTempest5": "Tempest Ring of Defense",
    "EquipmentRingsTempest6": "Tempest Ring of Gold",
    "EquipmentRingsTempest7": "Tempest Ring of Death",
    "EquipmentRingsTempest8": "Tempest Ring of Punchies",
    "EquipmentShirts1": "Orange Tee",
    "EquipmentShirts10": "Fur Shirt",
    "EquipmentShirts11": "Copper Platebody",
    "EquipmentShirts12": "Iron Platebody",
    "EquipmentShirts13": "Gold Platebody",
    "EquipmentShirts14": "Platinum Platbody",
    "EquipmentShirts15": "Dementia Body",
    "EquipmentShirts16": "Spore Tee",
    "EquipmentShirts17": "MCR Tshirt",
    "EquipmentShirts18": "Amarok Bodyplate",
    "EquipmentShirts19": "Planktop",
    "EquipmentShirts2": "Blue Tee",
    "EquipmentShirts20": "Hide Shirt",
    "EquipmentShirts21": "Tattered Cloth",
    "EquipmentShirts22": "Furled Robes",
    "EquipmentShirts23": "Feral Leathering",
    "EquipmentShirts24": "Green Tee",
    "EquipmentShirts25": "Purple Tee",
    "EquipmentShirts26": "Efaunt Ribcage",
    "EquipmentShirts27": "Void Imperium Platebody",
    "EquipmentShirts28": "Damascus Plates",
    "EquipmentShirts29": "Evergreen Wraps",
    "EquipmentShirts3": "Black Tee",
    "EquipmentShirts30": "Elegantine Robes",
    "EquipmentShirts31": "Member Hoodie",
    "EquipmentShirts32": "Lustre Chestplate",
    "EquipmentShirts33": "Diabolical Abdomen",
    "EquipmentShirts34": "Trollish Garb",
    "EquipmentShirts35": "Magma Core Wavemaille",
    "EquipmentShirts36": "Serrated Chest of the Divine",
    "EquipmentShirts37": "Marbiglass Tunic",
    "EquipmentShirts38": "Robe of the Gods",
    "EquipmentShirts39": "Emperor Sokutai Ho",
    "EquipmentShirts4": "Tanned Hide",
    "EquipmentShirts40": "Mining Overalls",
    "EquipmentShirts41": "Prehistoric Parka",
    "EquipmentShirts5": "Studded Hide",
    "EquipmentShirts6": "Chizoar Bodyplate",
    "EquipmentShirts7": "Molten Chest",
    "EquipmentShirts8": "REPLACE ME",
    "EquipmentShirts9": "REPLACE ME",
    "EquipmentShoes1": "Copper Boots",
    "EquipmentShoes10": "Flap Flops",
    "EquipmentShoes11": "Floop Flops",
    "EquipmentShoes12": "Flux Flops",
    "EquipmentShoes13": "Gaia Shoes",
    "EquipmentShoes14": "Cauldrunners",
    "EquipmentShoes15": "Iron Boots",
    "EquipmentShoes16": "Cavern Trekkers",
    "EquipmentShoes17": "Logger Heels",
    "EquipmentShoes18": "Angler Boots",
    "EquipmentShoes19": "Bandito Boots",
    "EquipmentShoes2": "Eyern Boots",
    "EquipmentShoes20": "Amarok Paws",
    "EquipmentShoes21": "Efaunts Broken Ankles",
    "EquipmentShoes22": "Void Imperium Kicks",
    "EquipmentShoes23": "Chizoar Walkers",
    "EquipmentShoes24": "Lustre Shieldshoe",
    "EquipmentShoes25": "Diabolical Toe Tips",
    "EquipmentShoes26": "Rough Rockers",
    "EquipmentShoes27": "Fiberous Footings",
    "EquipmentShoes28": "Deep Sea Galoshes",
    "EquipmentShoes29": "Spaggy Westerados",
    "EquipmentShoes3": "Gold Boots",
    "EquipmentShoes30": "Cooking Clogs",
    "EquipmentShoes31": "Chef Hat Shoes",
    "EquipmentShoes32": "Laboratory Scrubs",
    "EquipmentShoes33": "Sheek Scrubs",
    "EquipmentShoes34": "Soles of the Troll",
    "EquipmentShoes35": "Magma Core Lavarunners",
    "EquipmentShoes36": "Devious Slippers of the Divine",
    "EquipmentShoes37": "Marbiglass Soles",
    "EquipmentShoes38": "Drip of the Gods",
    "EquipmentShoes39": "Divvy Slippers",
    "EquipmentShoes4": "Platinum Boots",
    "EquipmentShoes40": "Emperor Geta",
    "EquipmentShoes41": "Prehistoric Bracers",
    "EquipmentShoes5": "Dementia Boots",
    "EquipmentShoes6": "Hermes Boots",
    "EquipmentShoes7": "Goo Galoshes",
    "EquipmentShoes8": "Yeti Walkers",
    "EquipmentShoes9": "Flip Flops",
    "EquipmentSword1": "Enforced Slasher",
    "EquipmentSword10": "Sabertoothed Gorehacker",
    "EquipmentSword2": "The Ice Breaker",
    "EquipmentSword3": "Deuscythe",
    "EquipmentSword4": "Slimsharp Fin",
    "EquipmentSword5": "Diabolical Flesh Ripper",
    "EquipmentSword6": "Magma Maul",
    "EquipmentSword7": "Skull Lance",
    "EquipmentSword8": "Elegant Spear",
    "EquipmentSword9": "Massive Godbreaker",
    "EquipmentTools1": "Junk Pickaxe",
    "EquipmentTools10": "Poopy Pickaxe",
    "EquipmentTools11": "Void Imperium Pik",
    "EquipmentTools12": "Starfire Pickaxe",
    "EquipmentTools13": "Skewered Snek",
    "EquipmentTools14": "Marbiglass Pickaxe",
    "EquipmentTools15": "Destroyer of the Mollo Gomme",
    "EquipmentTools16": "Prehistoric Pickaxe",
    "EquipmentTools2": "Copper Pickaxe",
    "EquipmentTools3": "Iron Pickaxe",
    "EquipmentTools5": "Gold Pickaxe",
    "EquipmentTools6": "Platinum Pickaxe",
    "EquipmentTools7": "Dementia Pickaxe",
    "EquipmentTools8": "Lustre Pickaxe",
    "EquipmentTools9": "Dreadlo Pickolo",
    "EquipmentToolsHatchet0": "Old Hatchet",
    "EquipmentToolsHatchet1": "Iron Hatchet",
    "EquipmentToolsHatchet10": "Annihilator of the Yggdrasil",
    "EquipmentToolsHatchet11": "Grumbie the Hatchet Hammer",
    "EquipmentToolsHatchet12": "Marbiglass Hatchet",
    "EquipmentToolsHatchet13": "Prehistoric Choppah",
    "EquipmentToolsHatchet2": "Golden Axe",
    "EquipmentToolsHatchet2b": "Stinky Axe",
    "EquipmentToolsHatchet3": "Copper Chopper",
    "EquipmentToolsHatchet4": "Plat Hatchet",
    "EquipmentToolsHatchet5": "Dementia Dicer",
    "EquipmentToolsHatchet6": "Lustre Logger",
    "EquipmentToolsHatchet7": "Void Imperium Axe",
    "EquipmentToolsHatchet8": "Starfire Hatchet",
    "EquipmentToolsHatchet9": "Dreadlo Hatchet",
    "EquipmentWands1": "Gnarled Wand",
    "EquipmentWands10": "Cattle Core Soothsayer Staff",
    "EquipmentWands11": "Staff of the Undead Plague",
    "EquipmentWands12": "Sparky Marble Staff",
    "EquipmentWands13": "Magnifique Godcaster",
    "EquipmentWands14": "Beastly Orblauncher",
    "EquipmentWands2": "Quarterstaff",
    "EquipmentWands3": "Spriggly Storm",
    "EquipmentWands4": "Microphone",
    "EquipmentWands5": "Starlight",
    "EquipmentWands6": "Crows Nest",
    "EquipmentWands7": "Grey Gatsby",
    "EquipmentWands8": "Skullslip Hallow",
    "EquipmentWands9": "Diabolical Opticule",
    "EquipmentWandsArc0": "Arcanist Staff",
    "FishingRod1": "Wood Fishing Rod",
    "FishingRod10": "Dreadlo Rod",
    "FishingRod11": "Marbiglass Rod",
    "FishingRod12": "Angler of the Iliunne",
    "FishingRod13": "Prehistoric Rod",
    "FishingRod2": "Copper Fish Rod",
    "FishingRod3": "Iron Fishing Rod",
    "FishingRod4": "Gold Fishing Rod",
    "FishingRod5": "Plat Fishing Rod",
    "FishingRod6": "Dementia Rod for Fishing",
    "FishingRod7": "Void Imperium Rod",
    "FishingRod8": "Lustre Rod",
    "FishingRod9": "Starfire Rod",
    "TrapBoxSet1": "Cardboard Traps",
    "TrapBoxSet10": "Containment of the Zrgyios",
    "TrapBoxSet11": "Prehistoric Traps",
    "TrapBoxSet2": "Silkskin Traps",
    "TrapBoxSet3": "Wooden Traps",
    "TrapBoxSet4": "Natural Traps",
    "TrapBoxSet5": "Steel Traps",
    "TrapBoxSet6": "Meaty Traps",
    "TrapBoxSet7": "Royal Traps",
    "TrapBoxSet8": "Egalitarian Traps",
    "TrapBoxSet9": "Forbidden Traps",
    "Trophy1": "King of Food",
    "Trophy10": "Critter Baron",
    "Trophy11": "YumYum Sheriff",
    "Trophy12": "Megalodon",
    "Trophy13": "Club Maestro",
    "Trophy14": "Beach Bro",
    "Trophy15": "Frost Prince",
    "Trophy16": "Idle Skiller",
    "Trophy17": "One of the Divine",
    "Trophy18": "Master of Nothing",
    "Trophy19": "Nebula Royal",
    "Trophy2": "Lucky Lad",
    "Trophy20": "Luckier Lad",
    "Trophy21": "Baller",
    "Trophy22": "Gladiator",
    "Trophy23": "Heroic Spirit",
    "Trophy24": "Nine Dart Finish",
    "Trophy25": "Luckiest Lad",
    "Trophy3": "Club Member",
    "Trophy4": "I Made This Game",
    "Trophy5": "Dice Dynamo",
    "Trophy6": "Blunder Hero",
    "Trophy7": "Original Gamer",
    "Trophy8": "Trailblazer",
    "Trophy9": "Ultra Unboxer",
    "TrophyReplica0": "Replica Trophy",
    "TrophyReplica1": "King of Food",
    "TrophyReplica10": "Critter Baron",
    "TrophyReplica11": "YumYum Sheriff",
    "TrophyReplica12": "Megalodon",
    "TrophyReplica13": "Club Maestro",
    "TrophyReplica14": "Beach Bro",
    "TrophyReplica15": "Frost Prince",
    "TrophyReplica16": "Idle Skiller",
    "TrophyReplica17": "One of the Divine",
    "TrophyReplica18": "Master of Nothing",
    "TrophyReplica19": "Nebula Royal",
    "TrophyReplica2": "Lucky Lad",
    "TrophyReplica20": "Luckier Lad",
    "TrophyReplica21": "Baller",
    "TrophyReplica22": "Gladiator",
    "TrophyReplica23": "Heroic Spirit",
    "TrophyReplica24": "Nine Dart Finish",
    "TrophyReplica25": "Nine Dart Finish",
    "TrophyReplica3": "Club Member",
    "TrophyReplica4": "I Made This Game",
    "TrophyReplica5": "Dice Dynamo",
    "TrophyReplica6": "Blunder Hero",
    "TrophyReplica7": "Original Gamer",
    "TrophyReplica8": "Trailblazer",
    "TrophyReplica9": "Ultra Unboxer",
    "WorshipSkull1": "Wax Skull",
    "WorshipSkull10": "Cultist Skull",
    "WorshipSkull11": "Crystal Skull of Esquire Vnoze",
    "WorshipSkull12": "Prehistoric Skull",
    "WorshipSkull2": "Ceramic Skull",
    "WorshipSkull3": "Horned Skull",
    "WorshipSkull4": "Prickle Skull",
    "WorshipSkull5": "Manifested Skull",
    "WorshipSkull6": "Glauss Skull",
    "WorshipSkull7": "Luciferian Skull",
    "WorshipSkull8": "Slush Skull",
    "WorshipSkull9": "Dreadnaught Skull",
}

EQUIPMENT_ITEM_ASSETS = {
    "CatchingNet1": "equipment/catching_net/bug_net.png",
    "CatchingNet10": "equipment/catching_net/dreadlo_matted_netting.png",
    "CatchingNet11": "equipment/catching_net/marbiglass_netting.png",
    "CatchingNet12": "equipment/catching_net/wrangler_of_the_qoxzul.png",
    "CatchingNet13": "equipment/catching_net/prehistoric_netting.png",
    "CatchingNet2": "equipment/catching_net/copper_netted_net.png",
    "CatchingNet3": "equipment/catching_net/reinforced_net.png",
    "CatchingNet4": "equipment/catching_net/golden_net.png",
    "CatchingNet5": "equipment/catching_net/platinet.png",
    "CatchingNet6": "equipment/catching_net/dementia_net.png",
    "CatchingNet7": "equipment/catching_net/void_imperium_net.png",
    "CatchingNet8": "equipment/catching_net/lustre_netting.png",
    "CatchingNet9": "equipment/catching_net/starfire_trim_netting.png",
    "DNAgun0": "equipment/dna_splicer/sappy_dna_splicer.png",
    "DNAgun1": "equipment/dna_splicer/bolstered_dna_splicer.png",
    "DNAgun2": "equipment/dna_splicer/double_barreled_dna_splicer.png",
    "DNAgun3": "equipment/dna_splicer/ergonomic_dna_splicer.png",
    "EquipmentBows1": "equipment/bow/wooden_bow.png",
    "EquipmentBows10": "equipment/bow/diabolical_continuit.png",
    "EquipmentBows11": "equipment/bow/sediment_core_grunkler.png",
    "EquipmentBows12": "equipment/bow/spine_tingler_sniper.png",
    "EquipmentBows13": "equipment/bow/pristine_longbow.png",
    "EquipmentBows14": "equipment/bow/doublestring_godshooter.png",
    "EquipmentBows15": "equipment/bow/raptor_shardslinger.png",
    "EquipmentBows3": "equipment/bow/birch_longbow.png",
    "EquipmentBows4": "equipment/bow/carrot_launcher.png",
    "EquipmentBows5": "equipment/bow/spiked_menace.png",
    "EquipmentBows6": "equipment/bow/pharaoh_bow.png",
    "EquipmentBows7": "equipment/bow/blizzard_bow.png",
    "EquipmentBows8": "equipment/bow/blackhole_bow.png",
    "EquipmentBows9": "equipment/bow/shardsure_leif.png",
    "EquipmentBowsTempest0": "equipment/bow/tempest_bow_of_dust.png",
    "EquipmentBowsTempest1": "equipment/bow/tempest_bow_of_ice.png",
    "EquipmentBowsTempest2": "equipment/bow/tempest_bow_of_fire.png",
    "EquipmentBowsTempest3": "equipment/bow/tempest_bow_of_wind.png",
    "EquipmentBowsTempest4": "equipment/bow/tempest_bow_of_grass.png",
    "EquipmentCape0": "equipment/cape/angel_wings.png",
    "EquipmentCape1": "equipment/cape/lava_wings.png",
    "EquipmentCape10": "equipment/cape/giant_starflower.png",
    "EquipmentCape11": "equipment/cape/riftwalker_wings.png",
    "EquipmentCape12": "equipment/cape/blooming_vine.png",
    "EquipmentCape13": "equipment/cape/eternal_flames_of_the_divine.png",
    "EquipmentCape14": "equipment/cape/phoenix_wings.png",
    "EquipmentCape15": "equipment/cape/giant_nightshade.png",
    "EquipmentCape16": "equipment/cape/timeless_watch.png",
    "EquipmentCape17": "equipment/cape/gilded_emperor_wings.png",
    "EquipmentCape18": "equipment/cape/chains_of_the_gilded_vaultguard.png",
    "EquipmentCape19": "equipment/cape/dragonroll_mantlepiece.png",
    "EquipmentCape2": "equipment/cape/easter_egg_backpack.png",
    "EquipmentCape20": "equipment/cape/beeg_egg.png",
    "EquipmentCape3": "equipment/cape/radiant_amarok_backstabber.png",
    "EquipmentCape4": "equipment/cape/gilded_efaunt_dislodged_tusks.png",
    "EquipmentCape5": "equipment/cape/blighted_chizoar_shard_cape.png",
    "EquipmentCape6": "equipment/cape/cascading_scaled_cape_of_krieg.png",
    "EquipmentCape7": "equipment/cape/molten_cloak.png",
    "EquipmentCape8": "equipment/cape/giant_rose.png",
    "EquipmentCape9": "equipment/cape/giant_violet.png",
    "EquipmentGown0": "equipment/gown/pyromancer_robes.png",
    "EquipmentGown1": "equipment/gown/cobalt_robe.png",
    "EquipmentGown2": "equipment/gown/abyssal_robe.png",
    "EquipmentGown3": "equipment/gown/evergreen_robe.png",
    "EquipmentGown4": "equipment/gown/silkshard_robe.png",
    "EquipmentGown5": "equipment/gown/corsair_uniform.png",
    "EquipmentGown6": "equipment/gown/bulwark_armor.png",
    "EquipmentGown7": "equipment/gown/time_traveler_outfit.png",
    "EquipmentHats1": "equipment/hat/farmer_brim.png",
    "EquipmentHats10": "equipment/hat/pink_headband.png",
    "EquipmentHats100": "equipment/hat/fiery_mane.png",
    "EquipmentHats101": "equipment/hat/guardian_mane.png",
    "EquipmentHats102": "equipment/hat/fanned_blossomage.png",
    "EquipmentHats103": "equipment/hat/dainty_brim.png",
    "EquipmentHats104": "equipment/hat/charcoal_hat.png",
    "EquipmentHats105": "equipment/hat/marbiglass_headdress.png",
    "EquipmentHats106": "equipment/hat/crown_of_the_gods.png",
    "EquipmentHats107": "equipment/hat/shiny_bored_beanie.png",
    "EquipmentHats108": "equipment/hat/3rd_anniversary_ice_cream_topper.png",
    "EquipmentHats109": "equipment/hat/husky_hat.png",
    "EquipmentHats11": "equipment/hat/grey_beret.png",
    "EquipmentHats110": "equipment/hat/yellow_beanie.png",
    "EquipmentHats111": "equipment/hat/epic_santa_hat.png",
    "EquipmentHats112": "equipment/hat/deathbringer_hood_of_death.png",
    "EquipmentHats113": "equipment/hat/pink_beanie.png",
    "EquipmentHats114": "equipment/hat/true_crown.png",
    "EquipmentHats115": "equipment/hat/celebration_mane.png",
    "EquipmentHats116": "equipment/hat/goldberry.png",
    "EquipmentHats117": "equipment/hat/orange_beanie.png",
    "EquipmentHats118": "equipment/hat/windwalker_hood.png",
    "EquipmentHats119": "equipment/hat/emperor_kabuto.png",
    "EquipmentHats12": "equipment/hat/traffic_cone.png",
    "EquipmentHats120": "equipment/hat/umbrella_brim.png",
    "EquipmentHats121": "equipment/hat/bloo_creamer.png",
    "EquipmentHats122": "equipment/hat/arcanist_crown.png",
    "EquipmentHats123": "equipment/hat/prehistoric_battlehair.png",
    "EquipmentHats124": "equipment/hat/alpine_beanie.png",
    "EquipmentHats125": "equipment/hat/rudolph_antlers.png",
    "EquipmentHats126": "equipment/hat/helper_elf_hat.png",
    "EquipmentHats127": "equipment/hat/seal_team_skipper_hat.png",
    "EquipmentHats128": "equipment/hat/lovely_top_hat.png",
    "EquipmentHats129": "equipment/hat/polkadot_beanie.png",
    "EquipmentHats13": "equipment/hat/propeller_cap.png",
    "EquipmentHats130": "equipment/hat/leprechaun_hat.png",
    "EquipmentHats131": "equipment/hat/lucky_ducky_brim.png",
    "EquipmentHats132": "equipment/hat/time_traveler_top_hat.png",
    "EquipmentHats133": "equipment/hat/native_headdress.png",
    "EquipmentHats134": "equipment/hat/starry_hairpins.png",
    "EquipmentHats135": "equipment/hat/blonde_hairpiece.png",
    "EquipmentHats136": "equipment/hat/bronze_tournament_spike_hat.png",
    "EquipmentHats137": "equipment/hat/silver_tournament_spike_hat.png",
    "EquipmentHats138": "equipment/hat/gold_tournament_spike_hat.png",
    "EquipmentHats139": "equipment/hat/sun_hat.png",
    "EquipmentHats14": "equipment/hat/baseball_hat.png",
    "EquipmentHats15": "equipment/hat/leather_cap.png",
    "EquipmentHats16": "equipment/hat/top_hat.png",
    "EquipmentHats17": "equipment/hat/copper_helmet.png",
    "EquipmentHats18": "equipment/hat/iron_helmet.png",
    "EquipmentHats19": "equipment/hat/platinum_helmet.png",
    "EquipmentHats2": "equipment/hat/royal_turban.png",
    "EquipmentHats20": "equipment/hat/militia_helm.png",
    "EquipmentHats21": "equipment/hat/birthday_hat.png",
    "EquipmentHats22": "equipment/hat/amarok_helmet.png",
    "EquipmentHats23": "equipment/hat/farmer_brimer.png",
    "EquipmentHats24": "equipment/hat/farmer_brimest.png",
    "EquipmentHats25": "equipment/hat/bored_beanie.png",
    "EquipmentHats26": "equipment/hat/witch_hat.png",
    "EquipmentHats27": "equipment/hat/paper_boat.png",
    "EquipmentHats28": "equipment/hat/gold_helmet.png",
    "EquipmentHats29": "equipment/hat/alien_headband.png",
    "EquipmentHats3": "equipment/hat/thief_hood.png",
    "EquipmentHats30": "equipment/hat/cowbo_galloneer.png",
    "EquipmentHats31": "equipment/hat/smittys_bubble_blowing_hat.png",
    "EquipmentHats32": "equipment/hat/bandit_bob_mask.png",
    "EquipmentHats33": "equipment/hat/paper_bag.png",
    "EquipmentHats34": "equipment/hat/parasite.png",
    "EquipmentHats35": "equipment/hat/diamond_horns.png",
    "EquipmentHats36": "equipment/hat/halloween_pumpkin.png",
    "EquipmentHats37": "equipment/hat/hotdog_hero.png",
    "EquipmentHats38": "equipment/hat/invisible_hat.png",
    "EquipmentHats39": "equipment/hat/grandma_disguise.png",
    "EquipmentHats40": "equipment/hat/pardoned_turkey.png",
    "EquipmentHats41": "equipment/hat/sleek_coif.png",
    "EquipmentHats42": "equipment/hat/santa_hat.png",
    "EquipmentHats43": "equipment/hat/snowman.png",
    "EquipmentHats44": "equipment/hat/jar.png",
    "EquipmentHats45": "equipment/hat/giftmas_tree.png",
    "EquipmentHats46": "equipment/hat/strawbiggy.png",
    "EquipmentHats47": "equipment/hat/pop_cat.png",
    "EquipmentHats48": "equipment/hat/dairy_dunk.png",
    "EquipmentHats49": "equipment/hat/the_classic.png",
    "EquipmentHats4Choppin": "equipment/hat/stump_prop.png",
    "EquipmentHats5": "equipment/hat/white_headband.png",
    "EquipmentHats50": "equipment/hat/green_beanie.png",
    "EquipmentHats51": "equipment/hat/big_pretty_bow.png",
    "EquipmentHats52": "equipment/hat/efaunt_helmet.png",
    "EquipmentHats53": "equipment/hat/dementia_helmet.png",
    "EquipmentHats54": "equipment/hat/void_imperium_helmet.png",
    "EquipmentHats55": "equipment/hat/steam_cap.png",
    "EquipmentHats56": "equipment/hat/bunny_ears.png",
    "EquipmentHats57": "equipment/hat/big_bunny.png",
    "EquipmentHats58": "equipment/hat/murmillo_helm.png",
    "EquipmentHats59": "equipment/hat/conquistador_plume.png",
    "EquipmentHats6": "equipment/hat/green_headband.png",
    "EquipmentHats60": "equipment/hat/adornment_of_the_high_priest.png",
    "EquipmentHats61": "equipment/hat/mark_of_member.png",
    "EquipmentHats62": "equipment/hat/fluffy_ramsy.png",
    "EquipmentHats63": "equipment/hat/summer_shell.png",
    "EquipmentHats64": "equipment/hat/nuget_cake_fedora.png",
    "EquipmentHats65": "equipment/hat/the_red_boaty.png",
    "EquipmentHats66": "equipment/hat/honker_hat.png",
    "EquipmentHats67": "equipment/hat/acorn_topper.png",
    "EquipmentHats68": "equipment/hat/chizoar_helmet.png",
    "EquipmentHats69": "equipment/hat/giftmas_snoozy_cap.png",
    "EquipmentHats7": "equipment/hat/red_headband.png",
    "EquipmentHats70": "equipment/hat/lustre_veil.png",
    "EquipmentHats71": "equipment/hat/diabolical_headcase.png",
    "EquipmentHats72": "equipment/hat/nondescript_game_show_host_hair.png",
    "EquipmentHats73": "equipment/hat/real_civil_engineer_helmet.png",
    "EquipmentHats74": "equipment/hat/thin_veil_of_the_troll.png",
    "EquipmentHats75": "equipment/hat/apple_launch_hat.png",
    "EquipmentHats76": "equipment/hat/funny_hat.png",
    "EquipmentHats77": "equipment/hat/magma_core_headdress.png",
    "EquipmentHats78": "equipment/hat/meteorhead.png",
    "EquipmentHats79": "equipment/hat/ice_guard_helmet.png",
    "EquipmentHats8": "equipment/hat/purple_tupacband.png",
    "EquipmentHats80": "equipment/hat/corgi_topper.png",
    "EquipmentHats81": "equipment/hat/siege_captain_cap.png",
    "EquipmentHats82": "equipment/hat/ele_sorcerer_pointed_hat.png",
    "EquipmentHats83": "equipment/hat/skulled_helmet_of_the_divine.png",
    "EquipmentHats84": "equipment/hat/the_crow_perch.png",
    "EquipmentHats85": "equipment/hat/bedsheet_with_holes.png",
    "EquipmentHats86": "equipment/hat/carrotman_mask.png",
    "EquipmentHats87": "equipment/hat/glublin_mask.png",
    "EquipmentHats88": "equipment/hat/bloque_mask.png",
    "EquipmentHats89": "equipment/hat/borzoi_topper.png",
    "EquipmentHats9": "equipment/hat/yellow_headband.png",
    "EquipmentHats90": "equipment/hat/straw_hat.png",
    "EquipmentHats91": "equipment/hat/wig_bandana.png",
    "EquipmentHats92": "equipment/hat/funky_hat.png",
    "EquipmentHats93": "equipment/hat/reinforced_headband.png",
    "EquipmentHats94": "equipment/hat/shogun_helmet.png",
    "EquipmentHats95": "equipment/hat/gilded_headband.png",
    "EquipmentHats96": "equipment/hat/bamboo_hat.png",
    "EquipmentHats97": "equipment/hat/festive_beast_mask.png",
    "EquipmentHats98": "equipment/hat/heiress_headdress.png",
    "EquipmentHats99": "equipment/hat/spirited_mane.png",
    "EquipmentHatsBeg1": "equipment/hat/ice_cream_sundae.png",
    "EquipmentKeychain0": "equipment/keychain/simple_key_chain.png",
    "EquipmentKeychain1": "equipment/keychain/leafy_chain.png",
    "EquipmentKeychain10": "equipment/keychain/cactus_chain.png",
    "EquipmentKeychain11": "equipment/keychain/relic_chain.png",
    "EquipmentKeychain12": "equipment/keychain/balloon_dog_chain.png",
    "EquipmentKeychain13": "equipment/keychain/frozen_tart_chain.png",
    "EquipmentKeychain14": "equipment/keychain/whatamelon_chain.png",
    "EquipmentKeychain15": "equipment/keychain/9_ball_chain.png",
    "EquipmentKeychain16": "equipment/keychain/pincer_hand_chain.png",
    "EquipmentKeychain17": "equipment/keychain/gilded_key_chain.png",
    "EquipmentKeychain18": "equipment/keychain/sushi_chain.png",
    "EquipmentKeychain19": "equipment/keychain/time_candy_chain.png",
    "EquipmentKeychain2": "equipment/keychain/red_sneaker_chain.png",
    "EquipmentKeychain20": "equipment/keychain/star_blobulyte_galaxy_chain.png",
    "EquipmentKeychain21": "equipment/keychain/mmm_donut_chain.png",
    "EquipmentKeychain22": "equipment/keychain/negative_7_chain.png",
    "EquipmentKeychain23": "equipment/keychain/diamond_honker_chain.png",
    "EquipmentKeychain24": "equipment/keychain/bobgoldpickle_chain.png",
    "EquipmentKeychain25": "equipment/keychain/eye_owe_ess_chain.png",
    "EquipmentKeychain26": "equipment/keychain/key_to_desert_chain.png",
    "EquipmentKeychain27": "equipment/keychain/key_to_mountains_chain.png",
    "EquipmentKeychain28": "equipment/keychain/key_to_purgatory_chain.png",
    "EquipmentKeychain29": "equipment/keychain/spiritlord_horn_chain.png",
    "EquipmentKeychain3": "equipment/keychain/wartooth_chain.png",
    "EquipmentKeychain4": "equipment/keychain/8_ball_chain.png",
    "EquipmentKeychain5": "equipment/keychain/piggy_chain.png",
    "EquipmentKeychain6": "equipment/keychain/dumbphone_chain.png",
    "EquipmentKeychain7": "equipment/keychain/horn_chain.png",
    "EquipmentKeychain8": "equipment/keychain/rustic_key_chain.png",
    "EquipmentKeychain9": "equipment/keychain/taco_chain.png",
    "EquipmentNametag1": "equipment/name_tag/riftwalker.png",
    "EquipmentNametag10": "equipment/name_tag/3rd_anniversary_idleon.png",
    "EquipmentNametag11": "equipment/name_tag/nightshade.png",
    "EquipmentNametag12": "equipment/name_tag/megafeather.png",
    "EquipmentNametag13": "equipment/name_tag/timeless.png",
    "EquipmentNametag14": "equipment/name_tag/snowflake.png",
    "EquipmentNametag15": "equipment/name_tag/frostyman.png",
    "EquipmentNametag16": "equipment/name_tag/lovely_day.png",
    "EquipmentNametag17": "equipment/name_tag/spectacular_4th_year.png",
    "EquipmentNametag18": "equipment/name_tag/4th_anniversary_idleon.png",
    "EquipmentNametag19": "equipment/name_tag/aethermoon.png",
    "EquipmentNametag2": "equipment/name_tag/lavas_awesome.png",
    "EquipmentNametag20": "equipment/name_tag/deadbones.png",
    "EquipmentNametag21": "equipment/name_tag/treasure.png",
    "EquipmentNametag22": "equipment/name_tag/tome_apprentice.png",
    "EquipmentNametag23": "equipment/name_tag/tome_journeyman.png",
    "EquipmentNametag24": "equipment/name_tag/tome_expert.png",
    "EquipmentNametag25": "equipment/name_tag/tome_elite.png",
    "EquipmentNametag26": "equipment/name_tag/tome_pro.png",
    "EquipmentNametag27": "equipment/name_tag/tome_master.png",
    "EquipmentNametag28": "equipment/name_tag/tome_legend.png",
    "EquipmentNametag29": "equipment/name_tag/reliquarium.png",
    "EquipmentNametag3": "equipment/name_tag/balling.png",
    "EquipmentNametag30": "equipment/name_tag/cropfall.png",
    "EquipmentNametag31": "equipment/name_tag/gingerbread.png",
    "EquipmentNametag32": "equipment/name_tag/sweet_chocolate.png",
    "EquipmentNametag33": "equipment/name_tag/pot_of_gold.png",
    "EquipmentNametag34": "equipment/name_tag/emerald.png",
    "EquipmentNametag35": "equipment/name_tag/5th_anniversary_idleon.png",
    "EquipmentNametag36": "equipment/name_tag/wonderful_5th_year.png",
    "EquipmentNametag37": "equipment/name_tag/grand_egg.png",
    "EquipmentNametag4": "equipment/name_tag/vman.png",
    "EquipmentNametag41": "equipment/name_tag/all_that_glitters.png",
    "EquipmentNametag5": "equipment/name_tag/spring_flowers.png",
    "EquipmentNametag6b": "equipment/name_tag/trash_tuna.png",
    "EquipmentNametag7": "equipment/name_tag/island_adventurer.png",
    "EquipmentNametag8": "equipment/name_tag/summer_shovel.png",
    "EquipmentNametag9": "equipment/name_tag/falloween.png",
    "EquipmentNametagReplica1": "equipment/name_tag/riftwalker.png",
    "EquipmentNametagReplica10": "equipment/name_tag/3rd_anniversary_idleon.png",
    "EquipmentNametagReplica11": "equipment/name_tag/nightshade.png",
    "EquipmentNametagReplica12": "equipment/name_tag/megafeather.png",
    "EquipmentNametagReplica13": "equipment/name_tag/timeless.png",
    "EquipmentNametagReplica14": "equipment/name_tag/snowflake.png",
    "EquipmentNametagReplica15": "equipment/name_tag/frostyman.png",
    "EquipmentNametagReplica16": "equipment/name_tag/lovely_day.png",
    "EquipmentNametagReplica17": "equipment/name_tag/spectacular_4th_year.png",
    "EquipmentNametagReplica18": "equipment/name_tag/4th_anniversary_idleon.png",
    "EquipmentNametagReplica19": "equipment/name_tag/aethermoon.png",
    "EquipmentNametagReplica2": "equipment/name_tag/lavas_awesome.png",
    "EquipmentNametagReplica20": "equipment/name_tag/deadbones.png",
    "EquipmentNametagReplica21": "equipment/name_tag/treasure.png",
    "EquipmentNametagReplica22": "equipment/name_tag/tome_apprentice.png",
    "EquipmentNametagReplica23": "equipment/name_tag/tome_journeyman.png",
    "EquipmentNametagReplica24": "equipment/name_tag/tome_expert.png",
    "EquipmentNametagReplica25": "equipment/name_tag/tome_elite.png",
    "EquipmentNametagReplica26": "equipment/name_tag/tome_pro.png",
    "EquipmentNametagReplica27": "equipment/name_tag/tome_master.png",
    "EquipmentNametagReplica28": "equipment/name_tag/tome_legend.png",
    "EquipmentNametagReplica29": "equipment/name_tag/reliquarium.png",
    "EquipmentNametagReplica3": "equipment/name_tag/balling.png",
    "EquipmentNametagReplica30": "equipment/name_tag/cropfall.png",
    "EquipmentNametagReplica31": "equipment/name_tag/gingerbread.png",
    "EquipmentNametagReplica32": "equipment/name_tag/sweet_chocolate.png",
    "EquipmentNametagReplica33": "equipment/name_tag/pot_of_gold.png",
    "EquipmentNametagReplica34": "equipment/name_tag/emerald.png",
    "EquipmentNametagReplica35": "equipment/name_tag/5th_anniversary_idleon.png",
    "EquipmentNametagReplica36": "equipment/name_tag/wonderful_5th_year.png",
    "EquipmentNametagReplica37": "equipment/name_tag/grand_egg.png",
    "EquipmentNametagReplica4": "equipment/name_tag/vman.png",
    "EquipmentNametagReplica41": "equipment/name_tag/all_that_glitters.png",
    "EquipmentNametagReplica5": "equipment/name_tag/spring_flowers.png",
    "EquipmentNametagReplica6": "equipment/name_tag/trash_tuna.png",
    "EquipmentNametagReplica6b": "equipment/name_tag/trash_tuna.png",
    "EquipmentNametagReplica7": "equipment/name_tag/island_adventurer.png",
    "EquipmentNametagReplica8": "equipment/name_tag/summer_shovel.png",
    "EquipmentNametagReplica9": "equipment/name_tag/falloween.png",
    "EquipmentPants1": "equipment/pants/torn_jeans.png",
    "EquipmentPants10": "equipment/pants/give_up_on_life_pants.png",
    "EquipmentPants11": "equipment/pants/yellow_belt_ninja_pants.png",
    "EquipmentPants12": "equipment/pants/merchantile_pants.png",
    "EquipmentPants13": "equipment/pants/ancient_leggings.png",
    "EquipmentPants14": "equipment/pants/forensic_leggings.png",
    "EquipmentPants15": "equipment/pants/bleached_designer_wode_patch_pants.png",
    "EquipmentPants16": "equipment/pants/adams_leaf.png",
    "EquipmentPants17": "equipment/pants/amarok_hinds.png",
    "EquipmentPants18": "equipment/pants/dirty_coal_miner_baggy_soot_pants.png",
    "EquipmentPants19": "equipment/pants/trimmed_rune_platelegs.png",
    "EquipmentPants2": "equipment/pants/copper_platelegs.png",
    "EquipmentPants20": "equipment/pants/efaunt_hipilium.png",
    "EquipmentPants21": "equipment/pants/void_imperium_shardshins.png",
    "EquipmentPants22": "equipment/pants/fishing_overalls.png",
    "EquipmentPants23": "equipment/pants/bandito_pantaloon.png",
    "EquipmentPants24": "equipment/pants/lustre_scales.png",
    "EquipmentPants25": "equipment/pants/diabolical_trimed_leg_guards.png",
    "EquipmentPants26": "equipment/pants/magma_core_battleskirt.png",
    "EquipmentPants27": "equipment/pants/spiked_leggings_of_the_divine.png",
    "EquipmentPants29": "equipment/pants/marbiglass_legplates.png",
    "EquipmentPants3": "equipment/pants/iron_platelegs.png",
    "EquipmentPants30": "equipment/pants/tatters_of_the_gods.png",
    "EquipmentPants31": "equipment/pants/emperor_zubon.png",
    "EquipmentPants32": "equipment/pants/prehistoric_pantaloons.png",
    "EquipmentPants4": "equipment/pants/gold_platelegs.png",
    "EquipmentPants5": "equipment/pants/platinum_shins.png",
    "EquipmentPants6": "equipment/pants/dementia_shins.png",
    "EquipmentPants7": "equipment/pants/gilded_pilates.png",
    "EquipmentPants8": "equipment/pants/twisted_scales.png",
    "EquipmentPants9": "equipment/pants/chizoar_scaled_leggings.png",
    "EquipmentPendant1": "equipment/necklace/mint_icey.png",
    "EquipmentPendant10": "equipment/necklace/sleek_shank.png",
    "EquipmentPendant11": "equipment/necklace/carrot_horror.png",
    "EquipmentPendant12": "equipment/necklace/tarantulight.png",
    "EquipmentPendant13": "equipment/necklace/quartz_pendant.png",
    "EquipmentPendant14": "equipment/necklace/fuscismatia.png",
    "EquipmentPendant15": "equipment/necklace/lucky_fish_head.png",
    "EquipmentPendant16": "equipment/necklace/strung_bludgeon.png",
    "EquipmentPendant17": "equipment/necklace/chaotic_amarok_pendant.png",
    "EquipmentPendant18": "equipment/necklace/strung_steamy.png",
    "EquipmentPendant19": "equipment/necklace/cedar_pendant.png",
    "EquipmentPendant2": "equipment/necklace/strawbu_icey.png",
    "EquipmentPendant20": "equipment/necklace/fishhead_pendant.png",
    "EquipmentPendant21": "equipment/necklace/deathly_cluster_pendant.png",
    "EquipmentPendant22": "equipment/necklace/hallowed_tail_pendant.png",
    "EquipmentPendant23": "equipment/necklace/persephones_bouquet.png",
    "EquipmentPendant24": "equipment/necklace/chizoars_blankie.png",
    "EquipmentPendant25": "equipment/necklace/chizoars_caustic_scarf.png",
    "EquipmentPendant26": "equipment/necklace/polished_bludgeon.png",
    "EquipmentPendant27": "equipment/necklace/skullfish_pendant.png",
    "EquipmentPendant28": "equipment/necklace/crescent_moon_pendant.png",
    "EquipmentPendant29": "equipment/necklace/strung_tooth_of_the_divine.png",
    "EquipmentPendant3": "equipment/necklace/rok_road_icey.png",
    "EquipmentPendant30": "equipment/necklace/the_divine_scarf.png",
    "EquipmentPendant31": "equipment/necklace/deathbloom_flower_pendant.png",
    "EquipmentPendant32": "equipment/necklace/slimy_necklace.png",
    "EquipmentPendant33": "equipment/necklace/emerald_bling_pendant.png",
    "EquipmentPendant34": "equipment/necklace/charred_pendant.png",
    "EquipmentPendant35": "equipment/necklace/bramble_of_the_emperor.png",
    "EquipmentPendant36": "equipment/necklace/butterfly_pendant.png",
    "EquipmentPendant4": "equipment/necklace/rainbo_icey.png",
    "EquipmentPendant5": "equipment/necklace/chocotastic_icey.png",
    "EquipmentPendant6": "equipment/necklace/blubbery_icecream.png",
    "EquipmentPendant7": "equipment/necklace/lava_icey.png",
    "EquipmentPendant8": "equipment/necklace/legends_icey.png",
    "EquipmentPendant9": "equipment/necklace/little_wooden_katana.png",
    "EquipmentPunching1": "equipment/fist/boxing_gloves.png",
    "EquipmentPunching10": "equipment/fist/pentastud_slapper.png",
    "EquipmentPunching11": "equipment/fist/mittens_of_the_gods.png",
    "EquipmentPunching12": "equipment/fist/talon_of_the_hawk.png",
    "EquipmentPunching2": "equipment/fist/the_stingers.png",
    "EquipmentPunching3": "equipment/fist/bandage_wraps.png",
    "EquipmentPunching4": "equipment/fist/uninflated_glove.png",
    "EquipmentPunching5": "equipment/fist/eclectic_ordeal.png",
    "EquipmentPunching6": "equipment/fist/knuckle_sabers.png",
    "EquipmentPunching7": "equipment/fist/diabolical_gauntlet.png",
    "EquipmentPunching8": "equipment/fist/molten_core_knucklers.png",
    "EquipmentPunching9": "equipment/fist/crackled_skull_destroyer.png",
    "EquipmentRings1": "equipment/ring/gold_ring.png",
    "EquipmentRings10": "equipment/ring/spikeweed_ring.png",
    "EquipmentRings11": "equipment/ring/defenders_dignity.png",
    "EquipmentRings12": "equipment/ring/frisbee_ring.png",
    "EquipmentRings13": "equipment/ring/silver_stopwatch.png",
    "EquipmentRings14": "equipment/ring/dooble_goopi.png",
    "EquipmentRings15": "equipment/ring/sanic_ring.png",
    "EquipmentRings16": "equipment/ring/efaunt_trunculus.png",
    "EquipmentRings18": "equipment/ring/the_emperors_opal.png",
    "EquipmentRings19": "equipment/ring/bejeweled_ring.png",
    "EquipmentRings2": "equipment/ring/copper_band.png",
    "EquipmentRings20": "equipment/ring/rex_ring.png",
    "EquipmentRings21": "equipment/ring/elf_twist_ring.png",
    "EquipmentRings22": "equipment/ring/tenacity_ring.png",
    "EquipmentRings23": "equipment/ring/neutron_ice_ring.png",
    "EquipmentRings24": "equipment/ring/lab_ring.png",
    "EquipmentRings25": "equipment/ring/chef_ring.png",
    "EquipmentRings26": "equipment/ring/serrated_rex_ring.png",
    "EquipmentRings27": "equipment/ring/protectors_pride.png",
    "EquipmentRings28": "equipment/ring/midnight_stopwatch.png",
    "EquipmentRings29": "equipment/ring/dawn_stopwatch.png",
    "EquipmentRings3": "equipment/ring/steel_band.png",
    "EquipmentRings30": "equipment/ring/souped_lab_ring.png",
    "EquipmentRings31": "equipment/ring/tundra_killer_ring.png",
    "EquipmentRings32": "equipment/ring/nebula_killer_ring.png",
    "EquipmentRings33": "equipment/ring/dune_killer_ring.png",
    "EquipmentRings34": "equipment/ring/magma_killer_ring.png",
    "EquipmentRings35": "equipment/ring/zero_point_stopwatch.png",
    "EquipmentRings36": "equipment/ring/demented_emperor_opal.png",
    "EquipmentRings37": "equipment/ring/spirit_killer_ring.png",
    "EquipmentRings38": "equipment/ring/starstrut_ring.png",
    "EquipmentRings4": "equipment/ring/molden_crust.png",
    "EquipmentRings5": "equipment/ring/toxic_bubbles_band.png",
    "EquipmentRings6": "equipment/ring/death_wish.png",
    "EquipmentRings7": "equipment/ring/pugilist_demise.png",
    "EquipmentRings8": "equipment/ring/the_used_bandaid.png",
    "EquipmentRings9": "equipment/ring/chat_ring.png",
    "EquipmentRingsArc0": "equipment/ring/cultist_ring.png",
    "EquipmentRingsChat1": "equipment/ring/love_ring.png",
    "EquipmentRingsChat10": "equipment/ring/meteorite_ring.png",
    "EquipmentRingsChat11": "equipment/ring/equinox_ring.png",
    "EquipmentRingsChat12": "equipment/ring/tournament_ring.png",
    "EquipmentRingsChat2": "equipment/ring/leafy_ring.png",
    "EquipmentRingsChat3": "equipment/ring/wealth_ring.png",
    "EquipmentRingsChat4": "equipment/ring/bob_ring.png",
    "EquipmentRingsChat5": "equipment/ring/bubble_ring.png",
    "EquipmentRingsChat6": "equipment/ring/cthulus_ring.png",
    "EquipmentRingsChat9": "equipment/ring/honk_ring.png",
    "EquipmentRingsFishing1": "equipment/ring/shallow_watering.png",
    "EquipmentRingsFishing2": "equipment/ring/oceanic_ring.png",
    "EquipmentRingsFishing3": "equipment/ring/deepwater_trench_ring.png",
    "EquipmentRingsTempest0": "equipment/ring/tempest_ring_of_leef.png",
    "EquipmentRingsTempest1": "equipment/ring/tempest_ring_of_ice.png",
    "EquipmentRingsTempest2": "equipment/ring/tempest_ring_of_lava.png",
    "EquipmentRingsTempest3": "equipment/ring/tempest_ring_of_carbon.png",
    "EquipmentRingsTempest4": "equipment/ring/tempest_ring_of_power.png",
    "EquipmentRingsTempest5": "equipment/ring/tempest_ring_of_defense.png",
    "EquipmentRingsTempest6": "equipment/ring/tempest_ring_of_gold.png",
    "EquipmentRingsTempest7": "equipment/ring/tempest_ring_of_death.png",
    "EquipmentRingsTempest8": "equipment/ring/tempest_ring_of_punchies.png",
    "EquipmentShirts1": "equipment/shirt/orange_tee.png",
    "EquipmentShirts10": "equipment/shirt/fur_shirt.png",
    "EquipmentShirts11": "equipment/shirt/copper_platebody.png",
    "EquipmentShirts12": "equipment/shirt/iron_platebody.png",
    "EquipmentShirts13": "equipment/shirt/gold_platebody.png",
    "EquipmentShirts14": "equipment/shirt/platinum_platbody.png",
    "EquipmentShirts15": "equipment/shirt/dementia_body.png",
    "EquipmentShirts16": "equipment/shirt/spore_tee.png",
    "EquipmentShirts17": "equipment/shirt/mcr_tshirt.png",
    "EquipmentShirts18": "equipment/shirt/amarok_bodyplate.png",
    "EquipmentShirts19": "equipment/shirt/planktop.png",
    "EquipmentShirts2": "equipment/shirt/blue_tee.png",
    "EquipmentShirts20": "equipment/shirt/hide_shirt.png",
    "EquipmentShirts21": "equipment/shirt/tattered_cloth.png",
    "EquipmentShirts22": "equipment/shirt/furled_robes.png",
    "EquipmentShirts23": "equipment/shirt/feral_leathering.png",
    "EquipmentShirts24": "equipment/shirt/green_tee.png",
    "EquipmentShirts25": "equipment/shirt/purple_tee.png",
    "EquipmentShirts26": "equipment/shirt/efaunt_ribcage.png",
    "EquipmentShirts27": "equipment/shirt/void_imperium_platebody.png",
    "EquipmentShirts28": "equipment/shirt/damascus_plates.png",
    "EquipmentShirts29": "equipment/shirt/evergreen_wraps.png",
    "EquipmentShirts3": "equipment/shirt/black_tee.png",
    "EquipmentShirts30": "equipment/shirt/elegantine_robes.png",
    "EquipmentShirts31": "equipment/shirt/member_hoodie.png",
    "EquipmentShirts32": "equipment/shirt/lustre_chestplate.png",
    "EquipmentShirts33": "equipment/shirt/diabolical_abdomen.png",
    "EquipmentShirts34": "equipment/shirt/trollish_garb.png",
    "EquipmentShirts35": "equipment/shirt/magma_core_wavemaille.png",
    "EquipmentShirts36": "equipment/shirt/serrated_chest_of_the_divine.png",
    "EquipmentShirts37": "equipment/shirt/marbiglass_tunic.png",
    "EquipmentShirts38": "equipment/shirt/robe_of_the_gods.png",
    "EquipmentShirts39": "equipment/shirt/emperor_sokutai_ho.png",
    "EquipmentShirts4": "equipment/shirt/tanned_hide.png",
    "EquipmentShirts40": "equipment/shirt/mining_overalls.png",
    "EquipmentShirts41": "equipment/shirt/prehistoric_parka.png",
    "EquipmentShirts5": "equipment/shirt/studded_hide.png",
    "EquipmentShirts6": "equipment/shirt/chizoar_bodyplate.png",
    "EquipmentShirts7": "equipment/shirt/molten_chest.png",
    "EquipmentShirts8": "equipment/shirt/replace_me.png",
    "EquipmentShirts9": "equipment/shirt/replace_me.png",
    "EquipmentShoes1": "equipment/shoe/copper_boots.png",
    "EquipmentShoes10": "equipment/shoe/flap_flops.png",
    "EquipmentShoes11": "equipment/shoe/floop_flops.png",
    "EquipmentShoes12": "equipment/shoe/flux_flops.png",
    "EquipmentShoes13": "equipment/shoe/gaia_shoes.png",
    "EquipmentShoes14": "equipment/shoe/cauldrunners.png",
    "EquipmentShoes15": "equipment/shoe/iron_boots.png",
    "EquipmentShoes16": "equipment/shoe/cavern_trekkers.png",
    "EquipmentShoes17": "equipment/shoe/logger_heels.png",
    "EquipmentShoes18": "equipment/shoe/angler_boots.png",
    "EquipmentShoes19": "equipment/shoe/bandito_boots.png",
    "EquipmentShoes2": "equipment/shoe/eyern_boots.png",
    "EquipmentShoes20": "equipment/shoe/amarok_paws.png",
    "EquipmentShoes21": "equipment/shoe/efaunts_broken_ankles.png",
    "EquipmentShoes22": "equipment/shoe/void_imperium_kicks.png",
    "EquipmentShoes23": "equipment/shoe/chizoar_walkers.png",
    "EquipmentShoes24": "equipment/shoe/lustre_shieldshoe.png",
    "EquipmentShoes25": "equipment/shoe/diabolical_toe_tips.png",
    "EquipmentShoes26": "equipment/shoe/rough_rockers.png",
    "EquipmentShoes27": "equipment/shoe/fiberous_footings.png",
    "EquipmentShoes28": "equipment/shoe/deep_sea_galoshes.png",
    "EquipmentShoes29": "equipment/shoe/spaggy_westerados.png",
    "EquipmentShoes3": "equipment/shoe/gold_boots.png",
    "EquipmentShoes30": "equipment/shoe/cooking_clogs.png",
    "EquipmentShoes31": "equipment/shoe/chef_hat_shoes.png",
    "EquipmentShoes32": "equipment/shoe/laboratory_scrubs.png",
    "EquipmentShoes33": "equipment/shoe/sheek_scrubs.png",
    "EquipmentShoes34": "equipment/shoe/soles_of_the_troll.png",
    "EquipmentShoes35": "equipment/shoe/magma_core_lavarunners.png",
    "EquipmentShoes36": "equipment/shoe/devious_slippers_of_the_divine.png",
    "EquipmentShoes37": "equipment/shoe/marbiglass_soles.png",
    "EquipmentShoes38": "equipment/shoe/drip_of_the_gods.png",
    "EquipmentShoes39": "equipment/shoe/divvy_slippers.png",
    "EquipmentShoes4": "equipment/shoe/platinum_boots.png",
    "EquipmentShoes40": "equipment/shoe/emperor_geta.png",
    "EquipmentShoes41": "equipment/shoe/prehistoric_bracers.png",
    "EquipmentShoes5": "equipment/shoe/dementia_boots.png",
    "EquipmentShoes6": "equipment/shoe/hermes_boots.png",
    "EquipmentShoes7": "equipment/shoe/goo_galoshes.png",
    "EquipmentShoes8": "equipment/shoe/yeti_walkers.png",
    "EquipmentShoes9": "equipment/shoe/flip_flops.png",
    "EquipmentSword1": "equipment/sword/enforced_slasher.png",
    "EquipmentSword10": "equipment/sword/sabertoothed_gorehacker.png",
    "EquipmentSword2": "equipment/sword/the_ice_breaker.png",
    "EquipmentSword3": "equipment/sword/deuscythe.png",
    "EquipmentSword4": "equipment/sword/slimsharp_fin.png",
    "EquipmentSword5": "equipment/sword/diabolical_flesh_ripper.png",
    "EquipmentSword6": "equipment/sword/magma_maul.png",
    "EquipmentSword7": "equipment/sword/skull_lance.png",
    "EquipmentSword8": "equipment/sword/elegant_spear.png",
    "EquipmentSword9": "equipment/sword/massive_godbreaker.png",
    "EquipmentTools1": "equipment/pickaxe/junk_pickaxe.png",
    "EquipmentTools10": "equipment/pickaxe/poopy_pickaxe.png",
    "EquipmentTools11": "equipment/pickaxe/void_imperium_pik.png",
    "EquipmentTools12": "equipment/pickaxe/starfire_pickaxe.png",
    "EquipmentTools13": "equipment/pickaxe/skewered_snek.png",
    "EquipmentTools14": "equipment/pickaxe/marbiglass_pickaxe.png",
    "EquipmentTools15": "equipment/pickaxe/destroyer_of_the_mollo_gomme.png",
    "EquipmentTools16": "equipment/pickaxe/prehistoric_pickaxe.png",
    "EquipmentTools2": "equipment/pickaxe/copper_pickaxe.png",
    "EquipmentTools3": "equipment/pickaxe/iron_pickaxe.png",
    "EquipmentTools5": "equipment/pickaxe/gold_pickaxe.png",
    "EquipmentTools6": "equipment/pickaxe/platinum_pickaxe.png",
    "EquipmentTools7": "equipment/pickaxe/dementia_pickaxe.png",
    "EquipmentTools8": "equipment/pickaxe/lustre_pickaxe.png",
    "EquipmentTools9": "equipment/pickaxe/dreadlo_pickolo.png",
    "EquipmentToolsHatchet0": "equipment/axe/old_hatchet.png",
    "EquipmentToolsHatchet1": "equipment/axe/iron_hatchet.png",
    "EquipmentToolsHatchet10": "equipment/axe/annihilator_of_the_yggdrasil.png",
    "EquipmentToolsHatchet11": "equipment/axe/grumbie_the_hatchet_hammer.png",
    "EquipmentToolsHatchet12": "equipment/axe/marbiglass_hatchet.png",
    "EquipmentToolsHatchet13": "equipment/axe/prehistoric_choppah.png",
    "EquipmentToolsHatchet2": "equipment/axe/golden_axe.png",
    "EquipmentToolsHatchet2b": "equipment/axe/stinky_axe.png",
    "EquipmentToolsHatchet3": "equipment/axe/copper_chopper.png",
    "EquipmentToolsHatchet4": "equipment/axe/plat_hatchet.png",
    "EquipmentToolsHatchet5": "equipment/axe/dementia_dicer.png",
    "EquipmentToolsHatchet6": "equipment/axe/lustre_logger.png",
    "EquipmentToolsHatchet7": "equipment/axe/void_imperium_axe.png",
    "EquipmentToolsHatchet8": "equipment/axe/starfire_hatchet.png",
    "EquipmentToolsHatchet9": "equipment/axe/dreadlo_hatchet.png",
    "EquipmentWands1": "equipment/wand/gnarled_wand.png",
    "EquipmentWands10": "equipment/wand/cattle_core_soothsayer_staff.png",
    "EquipmentWands11": "equipment/wand/staff_of_the_undead_plague.png",
    "EquipmentWands12": "equipment/wand/sparky_marble_staff.png",
    "EquipmentWands13": "equipment/wand/magnifique_godcaster.png",
    "EquipmentWands14": "equipment/wand/beastly_orblauncher.png",
    "EquipmentWands2": "equipment/wand/quarterstaff.png",
    "EquipmentWands3": "equipment/wand/spriggly_storm.png",
    "EquipmentWands4": "equipment/wand/microphone.png",
    "EquipmentWands5": "equipment/wand/starlight.png",
    "EquipmentWands6": "equipment/wand/crows_nest.png",
    "EquipmentWands7": "equipment/wand/grey_gatsby.png",
    "EquipmentWands8": "equipment/wand/skullslip_hallow.png",
    "EquipmentWands9": "equipment/wand/diabolical_opticule.png",
    "EquipmentWandsArc0": "equipment/wand/arcanist_staff.png",
    "FishingRod1": "equipment/fishing_rod/wood_fishing_rod.png",
    "FishingRod10": "equipment/fishing_rod/dreadlo_rod.png",
    "FishingRod11": "equipment/fishing_rod/marbiglass_rod.png",
    "FishingRod12": "equipment/fishing_rod/angler_of_the_iliunne.png",
    "FishingRod13": "equipment/fishing_rod/prehistoric_rod.png",
    "FishingRod2": "equipment/fishing_rod/copper_fish_rod.png",
    "FishingRod3": "equipment/fishing_rod/iron_fishing_rod.png",
    "FishingRod4": "equipment/fishing_rod/gold_fishing_rod.png",
    "FishingRod5": "equipment/fishing_rod/plat_fishing_rod.png",
    "FishingRod6": "equipment/fishing_rod/dementia_rod_for_fishing.png",
    "FishingRod7": "equipment/fishing_rod/void_imperium_rod.png",
    "FishingRod8": "equipment/fishing_rod/lustre_rod.png",
    "FishingRod9": "equipment/fishing_rod/starfire_rod.png",
    "TrapBoxSet1": "equipment/trap_box/cardboard_traps.png",
    "TrapBoxSet10": "equipment/trap_box/containment_of_the_zrgyios.png",
    "TrapBoxSet11": "equipment/trap_box/prehistoric_traps.png",
    "TrapBoxSet2": "equipment/trap_box/silkskin_traps.png",
    "TrapBoxSet3": "equipment/trap_box/wooden_traps.png",
    "TrapBoxSet4": "equipment/trap_box/natural_traps.png",
    "TrapBoxSet5": "equipment/trap_box/steel_traps.png",
    "TrapBoxSet6": "equipment/trap_box/meaty_traps.png",
    "TrapBoxSet7": "equipment/trap_box/royal_traps.png",
    "TrapBoxSet8": "equipment/trap_box/egalitarian_traps.png",
    "TrapBoxSet9": "equipment/trap_box/forbidden_traps.png",
    "Trophy1": "equipment/trophy/king_of_food.png",
    "Trophy10": "equipment/trophy/critter_baron.png",
    "Trophy11": "equipment/trophy/yumyum_sheriff.png",
    "Trophy12": "equipment/trophy/megalodon.png",
    "Trophy13": "equipment/trophy/club_maestro.png",
    "Trophy14": "equipment/trophy/beach_bro.png",
    "Trophy15": "equipment/trophy/frost_prince.png",
    "Trophy16": "equipment/trophy/idle_skiller.png",
    "Trophy17": "equipment/trophy/one_of_the_divine.png",
    "Trophy18": "equipment/trophy/master_of_nothing.png",
    "Trophy19": "equipment/trophy/nebula_royal.png",
    "Trophy2": "equipment/trophy/lucky_lad.png",
    "Trophy20": "equipment/trophy/luckier_lad.png",
    "Trophy21": "equipment/trophy/baller.png",
    "Trophy22": "equipment/trophy/gladiator.png",
    "Trophy23": "equipment/trophy/heroic_spirit.png",
    "Trophy24": "equipment/trophy/nine_dart_finish.png",
    "Trophy25": "equipment/trophy/luckiest_lad.png",
    "Trophy3": "equipment/trophy/club_member.png",
    "Trophy4": "equipment/trophy/i_made_this_game.png",
    "Trophy5": "equipment/trophy/dice_dynamo.png",
    "Trophy6": "equipment/trophy/blunder_hero.png",
    "Trophy7": "equipment/trophy/original_gamer.png",
    "Trophy8": "equipment/trophy/trailblazer.png",
    "Trophy9": "equipment/trophy/ultra_unboxer.png",
    "TrophyReplica0": "equipment/trophy/replica.png",
    "TrophyReplica1": "equipment/trophy/king_of_food.png",
    "TrophyReplica10": "equipment/trophy/critter_baron.png",
    "TrophyReplica11": "equipment/trophy/yumyum_sheriff.png",
    "TrophyReplica12": "equipment/trophy/megalodon.png",
    "TrophyReplica13": "equipment/trophy/club_maestro.png",
    "TrophyReplica14": "equipment/trophy/beach_bro.png",
    "TrophyReplica15": "equipment/trophy/frost_prince.png",
    "TrophyReplica16": "equipment/trophy/idle_skiller.png",
    "TrophyReplica17": "equipment/trophy/one_of_the_divine.png",
    "TrophyReplica18": "equipment/trophy/master_of_nothing.png",
    "TrophyReplica19": "equipment/trophy/nebula_royal.png",
    "TrophyReplica2": "equipment/trophy/lucky_lad.png",
    "TrophyReplica20": "equipment/trophy/luckier_lad.png",
    "TrophyReplica21": "equipment/trophy/baller.png",
    "TrophyReplica22": "equipment/trophy/gladiator.png",
    "TrophyReplica23": "equipment/trophy/heroic_spirit.png",
    "TrophyReplica24": "equipment/trophy/nine_dart_finish.png",
    "TrophyReplica25": "equipment/trophy/luckiest_lad.png",
    "TrophyReplica3": "equipment/trophy/club_member.png",
    "TrophyReplica4": "equipment/trophy/i_made_this_game.png",
    "TrophyReplica5": "equipment/trophy/dice_dynamo.png",
    "TrophyReplica6": "equipment/trophy/blunder_hero.png",
    "TrophyReplica7": "equipment/trophy/original_gamer.png",
    "TrophyReplica8": "equipment/trophy/trailblazer.png",
    "TrophyReplica9": "equipment/trophy/ultra_unboxer.png",
    "WorshipSkull1": "equipment/worship_skull/wax_skull.png",
    "WorshipSkull10": "equipment/worship_skull/cultist_skull.png",
    "WorshipSkull11": "equipment/worship_skull/crystal_skull_of_esquire_vnoze.png",
    "WorshipSkull12": "equipment/worship_skull/prehistoric_skull.png",
    "WorshipSkull2": "equipment/worship_skull/ceramic_skull.png",
    "WorshipSkull3": "equipment/worship_skull/horned_skull.png",
    "WorshipSkull4": "equipment/worship_skull/prickle_skull.png",
    "WorshipSkull5": "equipment/worship_skull/manifested_skull.png",
    "WorshipSkull6": "equipment/worship_skull/glauss_skull.png",
    "WorshipSkull7": "equipment/worship_skull/luciferian_skull.png",
    "WorshipSkull8": "equipment/worship_skull/slush_skull.png",
    "WorshipSkull9": "equipment/worship_skull/dreadnaught_skull.png",
}


def base_equipment_item_id(raw_item: str) -> str:
    """Return the base item ID for replica cosmetic variants."""
    if raw_item.startswith("TrophyReplica"):
        return raw_item.replace("TrophyReplica", "Trophy", 1)
    if raw_item.startswith("EquipmentNametagReplica"):
        return raw_item.replace("EquipmentNametagReplica", "EquipmentNametag", 1)
    return raw_item


def equipment_display_label(raw_item: str, default: str | None = None) -> str | None:
    """Return a human-readable equipment label for a raw item ID."""
    if label := EQUIPMENT_ITEM_LABELS.get(raw_item):
        return label
    base_item = base_equipment_item_id(raw_item)
    if label := EQUIPMENT_ITEM_LABELS.get(base_item):
        return label
    return default


def equipment_asset_path(raw_item: str) -> str | None:
    """Return a relative static asset path for a raw equipment item ID."""
    if path := EQUIPMENT_ITEM_ASSETS.get(raw_item):
        return path
    return EQUIPMENT_ITEM_ASSETS.get(base_equipment_item_id(raw_item))
